// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace App.Tenant.Entities
{
    public partial class SharedTenantContext : DbContext
    {
        public SharedTenantContext()
        {
        }

        public SharedTenantContext(DbContextOptions<SharedTenantContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Tenant> Tenant { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Tenant>(entity =>
            {
                entity.Property(e => e.ConnectionString)
                    .IsRequired()
                    .HasMaxLength(300);

                entity.Property(e => e.Domain)
                    .IsRequired()
                    .HasMaxLength(80);

                entity.Property(e => e.Logo)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}