// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Classes
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Intercessor { get; set; }

    public int TimeId { get; set; }

    public virtual ICollection<Servants> Servants { get; } = new List<Servants>();

    public virtual ICollection<Served> Served { get; } = new List<Served>();

    public virtual Time Time { get; set; }
}