// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities
{
    public partial class ServantWeek
    {
        public int ServentId { get; set; }
        public int WeekId { get; set; }
        public string Notes { get; set; }

        public virtual Servants Servent { get; set; }
        public virtual Weeks Week { get; set; }
    }
}