// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Services
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Classes> Classes { get; set; } = new List<Classes>();

    public virtual ICollection<Servants> Servants { get; set; } = new List<Servants>();
}