// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Served
{
    public int Id { get; set; }

    public int ClassId { get; set; }

    public string Name { get; set; }

    public string Photo { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string FatherOfConfession { get; set; }

    public DateTime? Birthday { get; set; }

    public virtual Classes Class { get; set; }

    public virtual ICollection<ServedWeeks> ServedWeeks { get; } = new List<ServedWeeks>();
}