// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Time
{
    public int Id { get; set; }

    public string Time1 { get; set; }

    public virtual ICollection<Classes> Classes { get; set; } = new List<Classes>();
}