// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities;

public partial class Weeks
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public virtual ICollection<ServantWeek> ServantWeek { get; set; } = new List<ServantWeek>();

    public virtual ICollection<ServedWeeks> ServedWeeks { get; set; } = new List<ServedWeeks>();
}