// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Core.Entities
{
    public partial class Weeks
    {
        public Weeks()
        {
            ServantWeek = new HashSet<ServantWeek>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Date { get; set; }

        public virtual ICollection<ServantWeek> ServantWeek { get; set; }
    }
}