// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.UI.Models
{
    public partial class Weeks
    {
        public Weeks()
        {
            Servant = new HashSet<Servants>();
            Served = new HashSet<Served>();
        }

        public int Id { get; set; }
        public DateTime Date { get; set; }

        public virtual ICollection<Servants> Servant { get; set; }
        public virtual ICollection<Served> Served { get; set; }
    }
}